theme: jekyll-theme-minimal
title: "Shuning Cheng"
description: "Counselor • Higher Education • Generative AI for Student Well‑Being"
logo: /assets/avatar.jpg
show_downloads: false

social_links:
  email: shuningcheng7@gmail.com
  cv: /assets/ShuningCheng_CV.pdf
