theme: jekyll-theme-minimal
title: "Shuning Cheng"
description: "Counselor • Higher Education • Immigration and transnationalism • Generative AI for Student Well‑Being"
logo: /assets/avatar_2.jpg
show_downloads: false

social_links:
  email: shuningcheng7@gmail.com
  github: https://github.com/sncheng7
  cv: /assets/ShuningCheng_CV.pdf
